224 - client history
fga-eps-mds/2020-2-SiGeD-Clients pull request #21
Opened 2021-04-26 00:41 UTC by vitorl-s

**Issue:** resolves fga-eps-mds/2020-2-SiGeD#224

## Descrição

Adicionando historico de clientes

2021-04-27 20:09 UTC, yukioz requested changes, later dismissed
O update client não está  adicionando as atualizações no histórico corretamente.

2021-04-27 20:09 UTC, yukioz commented on src/Controllers/ClientController.js
> +      clientHistory,
Trocar :

clientHistory  => history: clientHistory.

2021-04-30 23:21 UTC, EzequielDeOliveira approved these changes

2021-04-30 23:23 UTC, DaviMarinho approved these changes
LGTM!

2021-04-30 23:23 UTC, merged